import PDFDocument from 'pdfkit';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Generate PDF for Receipt (Stock In)
 */
export const generateReceiptPDF = (receipt, product, callback) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks = [];
  
  doc.on('data', chunk => chunks.push(chunk));
  doc.on('end', () => callback(Buffer.concat(chunks)));
  doc.on('error', err => callback(null, err));
  
  // Header
  doc.fontSize(24)
     .fillColor('#00072D')
     .text('STOCK RECEIPT', { align: 'center' });
  
  doc.moveDown();
  
  // Receipt Details
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Receipt ID: #${receipt.id}`, { continued: false })
     .text(`Date: ${new Date(receipt.date).toLocaleDateString('en-US', { 
       year: 'numeric', 
       month: 'long', 
       day: 'numeric',
       hour: '2-digit',
       minute: '2-digit'
     })}`)
     .text(`Status: ${receipt.status.toUpperCase()}`);
  
  doc.moveDown();
  
  // Supplier Information
  doc.fontSize(14)
     .fillColor('#00072D')
     .text('Supplier Information', { underline: true });
  
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Name: ${receipt.supplier_name}`);
  
  if (receipt.notes) {
    doc.text(`Notes: ${receipt.notes}`);
  }
  
  doc.moveDown();
  
  // Product Information
  doc.fontSize(14)
     .fillColor('#00072D')
     .text('Product Information', { underline: true });
  
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Product Name: ${product.name || 'N/A'}`)
     .text(`SKU: ${product.sku || 'N/A'}`)
     .text(`Category: ${product.category || 'N/A'}`);
  
  doc.moveDown();
  
  // Transaction Details
  doc.fontSize(14)
     .fillColor('#00072D')
     .text('Transaction Details', { underline: true });
  
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Quantity Received: ${receipt.quantity} units`);
  
  if (product.current_stock !== undefined) {
    doc.text(`Current Stock After Receipt: ${product.current_stock} units`);
  }
  
  doc.moveDown(2);
  
  // Footer
  doc.fontSize(10)
     .fillColor('#666666')
     .text('This is an automated receipt generated by Inventory Management System', 
           { align: 'center' });
  
  doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
  
  doc.end();
};

/**
 * Generate PDF for Delivery Note (Stock Out)
 */
export const generateDeliveryPDF = (delivery, product, callback) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks = [];
  
  doc.on('data', chunk => chunks.push(chunk));
  doc.on('end', () => callback(Buffer.concat(chunks)));
  doc.on('error', err => callback(null, err));
  
  // Header
  doc.fontSize(24)
     .fillColor('#00072D')
     .text('DELIVERY NOTE', { align: 'center' });
  
  doc.moveDown();
  
  // Delivery Details
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Delivery ID: #${delivery.id}`, { continued: false })
     .text(`Date: ${new Date(delivery.date).toLocaleDateString('en-US', { 
       year: 'numeric', 
       month: 'long', 
       day: 'numeric',
       hour: '2-digit',
       minute: '2-digit'
     })}`)
     .text(`Status: ${delivery.status.toUpperCase()}`);
  
  doc.moveDown();
  
  // Customer Information
  doc.fontSize(14)
     .fillColor('#00072D')
     .text('Customer Information', { underline: true });
  
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Name: ${delivery.customer_name}`);
  
  if (delivery.notes) {
    doc.text(`Notes: ${delivery.notes}`);
  }
  
  doc.moveDown();
  
  // Product Information
  doc.fontSize(14)
     .fillColor('#00072D')
     .text('Product Information', { underline: true });
  
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Product Name: ${product.name || 'N/A'}`)
     .text(`SKU: ${product.sku || 'N/A'}`)
     .text(`Category: ${product.category || 'N/A'}`);
  
  doc.moveDown();
  
  // Transaction Details
  doc.fontSize(14)
     .fillColor('#00072D')
     .text('Transaction Details', { underline: true });
  
  doc.fontSize(12)
     .fillColor('#000000')
     .text(`Quantity Delivered: ${delivery.quantity} units`);
  
  if (product.current_stock !== undefined) {
    doc.text(`Current Stock After Delivery: ${product.current_stock} units`);
  }
  
  doc.moveDown(2);
  
  // Footer
  doc.fontSize(10)
     .fillColor('#666666')
     .text('This is an automated delivery note generated by Inventory Management System', 
           { align: 'center' });
  
  doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
  
  doc.end();
};

/**
 * Generate PDF Report for Dashboard/Inventory Summary
 */
export const generateInventoryReportPDF = (data, callback) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks = [];
  
  doc.on('data', chunk => chunks.push(chunk));
  doc.on('end', () => callback(Buffer.concat(chunks)));
  doc.on('error', err => callback(null, err));
  
  // Header
  doc.fontSize(24)
     .fillColor('#00072D')
     .text('INVENTORY REPORT', { align: 'center' });
  
  doc.moveDown();
  
  doc.fontSize(10)
     .fillColor('#666666')
     .text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
  
  doc.moveDown(2);
  
  // Summary Statistics
  if (data.stats) {
    doc.fontSize(16)
       .fillColor('#00072D')
       .text('Summary Statistics', { underline: true });
    
    doc.fontSize(12)
       .fillColor('#000000')
       .text(`Total Products: ${data.stats.totalProducts || 0}`)
       .text(`Total Stock: ${data.stats.totalStock || 0} units`)
       .text(`Low Stock Items: ${data.stats.lowStockItems || 0}`)
       .text(`Out of Stock Items: ${data.stats.outOfStockItems || 0}`)
       .text(`Total Receipts: ${data.stats.totalReceipts || 0}`)
       .text(`Total Deliveries: ${data.stats.totalDeliveries || 0}`);
    
    doc.moveDown();
  }
  
  // Products List
  if (data.products && data.products.length > 0) {
    doc.fontSize(16)
       .fillColor('#00072D')
       .text('Products Inventory', { underline: true });
    
    doc.moveDown(0.5);
    
    data.products.forEach((product, index) => {
      doc.fontSize(10)
         .fillColor('#000000')
         .text(`${index + 1}. ${product.name} (SKU: ${product.sku})`, { indent: 20 })
         .text(`   Stock: ${product.current_stock} | Min: ${product.min_stock} | Category: ${product.category}`, 
               { indent: 30 });
      
      if (product.current_stock <= product.min_stock) {
        doc.fillColor('#FF0000')
           .text(`   ⚠️ LOW STOCK`, { indent: 30 });
        doc.fillColor('#000000');
      }
      
      doc.moveDown(0.3);
    });
  }
  
  doc.moveDown();
  
  // Footer
  doc.fontSize(10)
     .fillColor('#666666')
     .text('This is an automated report generated by Inventory Management System', 
           { align: 'center' });
  
  doc.end();
};

